# =============================================================================
# FLINK RBAC — ServiceAccount + IRSA (Staging)
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-sa
  namespace: flink
  labels:
    app.kubernetes.io/part-of: de-platform
    environment: staging
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/FlinkS3Role-Staging"
    eks.amazonaws.com/token-expiration: "86400"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-job-role
  namespace: flink
  labels:
    app.kubernetes.io/part-of: de-platform
    environment: staging
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["flink-processor", "de-kafka-cluster-cluster-ca-cert"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-job-rolebinding
  namespace: flink
  labels:
    app.kubernetes.io/part-of: de-platform
    environment: staging
subjects:
  - kind: ServiceAccount
    name: flink-sa
    namespace: flink
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: flink-job-role
