# =============================================================================
# EXTERNAL SECRETS OPERATOR — CLUSTER SECRET STORE (Staging)
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-staging
  labels:
    app.kubernetes.io/part-of: de-platform
    environment: staging
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets

  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
