apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: schema-registry-pdb
  namespace: schema-registry
  labels:
    app.kubernetes.io/part-of: de-platform
    environment: staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: apicurio-registry
